name: Build, lint, tests
on: [push, pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run CI tests
        run: npm run ci:test
