name: Build, lint, tests
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run Lint
        run: npm run lint
